### PR TITLE
feat: add optional scaffold-eth-cli command

### PR DESCRIPTION
**Pull request by QEDK**
This PR is intended as a temperature test for:
* providing traction to `scaffold-eth-cli` to further determine,
* if using `scaffold-eth-cli` is helpful for repeat iterators
  * think instead of having to find the right thing to clone everytime, you could simply do: `npx scaffold-eth nextjs-typescript` or `npx scaffold-eth <branch-name>`, maybe with some fuzzy searching algo
* if `scaffold-eth-cli` can be absorbed into the `scaffold-eth` org as a product to take forward 

cc @codenamejason @austintgriffith

### CODE REVIEW

**Comment by ghostffcode** [comment]
Is the repo for the CLI public?

**Comment by QEDK** [comment]
> Is the repo for the CLI public?

yep, see https://github.com/QEDK/scaffold-eth-cli

**Review by codenamejason — DISMISSED** [review]

**Comment by codenamejason** [comment]
I can make a repo under Scaffold-Eth for the cli code to live @QEDK wdyt?

**Comment by QEDK** [comment]
> I can make a repo under Scaffold-Eth for the cli code to live @QEDK wdyt?

works for me, I can transfer the repo to the org, but I would still like to remain as the code owner and maintainer, if that's okay.

**Pull request closed without merging**
