### PR TITLE
Improving header and account responsiveness

### PR DESCRIPTION
**Pull request by stevenpslade**
### What does this solving?

Currently the balance and address (in the `Account` component) overlap with the logo on smaller screens.

This PR introduces style and component changes that improve the header responsiveness as well as the general UI of the account component such as:
- smaller address and balance font size
- removing the fixed positioning of the account component in favour of using flex box styles in the `Header` component
- placing the long subtitle string under the main logo

**Desktop:**
image

**Phone screen:**
image

**Cluttered header with network selector also work most of the time:**
image

### CODE REVIEW

**Comment by codenamejason** [comment]
Screen Shot 2022-05-09 at 7 32 46 AM

Address not showing.

**Comment by stevenpslade** [comment]
> Screen Shot 2022-05-09 at 7 32 46 AM
> 
> Address not showing.

Oof 😮‍💨 
What browser? I like how _cleanly_ it doesn't show aha

**Comment by codenamejason** [comment]
was using chrome on a Mac

**Comment by codenamejason** [comment]
metamask

**Review by codenamejason — APPROVED** [review]

**Comment by codenamejason** [comment]
tried again fresh and all was good @stevenpslade

**Pull request merged**
