### PR TITLE
turned off autocomplete on inputs 

### PR DESCRIPTION
**Pull request by karbafoo**
redid everything and removed yarn.lock

### CODE REVIEW

**Comment by codenamejason** [comment]
yarn.lock still came through... ugh. not sure why this is happening.

**Comment by karbafoo** [comment]
theres no yarn.lock on my repo but theres one on scaffold-eth

**Comment by azf20** [comment]
yes @codenamejason this looks like it removes the yarn.lock

**Comment by codenamejason** [comment]
I can't resolve the conflicts for some reason @azf20

**Review by azf20 — APPROVED** [review]

**Review by codenamejason — APPROVED** [review]

**Comment by codenamejason** [comment]
@azf20 I cannot resolve the yarn.lock conflict... so I cannot merge. Why is yarn.lock even getting checked in...

**Pull request closed without merging**
