### PR TITLE
Add Optimism kovan and mainnet chain ids to transactor notify

### PR DESCRIPTION
**Pull request by damianmarti**

### CODE REVIEW

**Review by codenamejason — APPROVED** [review]
Thanks brother 🔥

**Comment by damianmarti** [comment]
@codenamejason I think that we should revert this PR. Notify doesn't support Optimism yet, so the callback set in the transaction doesn't called on every status change.

**Comment by codenamejason** [comment]
@damianmarti is is causing errors now for anyone? I can revert if they are.

**Comment by damianmarti** [comment]
@codenamejason Only if you are using Optimism network. If you add a callback on a Transactor call, this will not work as you expected since the callback will be called just one time and not one on each status change.

**Pull request merged**
