### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by skaunov**
a typo corrected

### CODE REVIEW

**Comment by codenamejason** [comment]
It is spelled that way on purpose, it's a crypto thing... @skaunov

**Comment by elshigori** [comment]
will know, thanks! )

**Comment by skaunov** [comment]
will know, thanks! )

**Comment by skaunov** [comment]
Pls, consider capitalizing it for canonical look. So it won't raise any grammatical response in people's heads. =)

**Pull request closed without merging**
