### PR TITLE
Sign-In with Ethereum Support (Blockin and Express.js)

### PR DESCRIPTION
**Pull request by trevormil**
### **Introduction to Sign-In with Ethereum** 
A quickly growing aspect of Ethereum development is EIP-4361 Sign-In with Ethereum (https://eips.ethereum.org/EIPS/eip-4361) which aims to "standardize off-chain authentication for Ethereum accounts to establish sessions".

Instead of using only Ethereum as your backend, many applications may want to use their own private database or backend to store some, if not all, of their data. This can be for many reasons such as privacy and scalability. For example, OpenSea doesn't store all their likes or watchlist data on-chain; they use their own private data stores in combination with Ethereum sign-in authentication.

Other Links:
-https://login.xyz/
-https://blog.spruceid.com/sign-in-with-ethereum-is-a-game-changer-part-1/

Also, we want to note that connecting and signing-in are two completely different concepts, as explained by the second link from above. Scaffold already supports connecting wallets but doesn't support signing-in.

### **Adding Another Flavor vs Main Template**
I was debating back and forth on whether to propose to add a new flavor of Scaffold ETH, such as the ones seen in the README. However, I think that supporting Sign-In with Ethereum is becoming a core part of Ethereum development, and as Scaffold ETH is aiming to be the all-in-one toolkit, I believe this pull request is better suited to be added to the main template repository.

### **Blockin**
Blockin is a library that was created by myself (a fellow BuidlGuidl member) and two other developers. Blockin aims to take the EIP-4361 Sign-In with Ethereum interface and extend it in the two following ways:
- Make it a multi-chain standard for all blockchains (not just Ethereum)
- Further support dynamic role-based access control by allowing on-chain assets (such as NFTs) to be included in sign-in requests and verified for ownership

These multi-chain capabilities are achieved through a generic ChainDriver interface where any logic custom to a blockchain can be implemented. Although Ethereum will be the only chain implemented in this pull request, Blockin makes it really easy for any developers who wish to extend their application to other blockchains in addition to Ethereum.

Additionally, Blockin aims to provide a suite of frontend UI tools to support all stages of the authorization process, such as a ChainSelect, all-in-one BlockinUIDisplay, and SignInModal. 

Links:
- Code Repositories: https://github.com/Blockin-Labs
- Docs: https://blockin.gitbook.io/blockin/
- Demo Site: https://blockin.vercel.app/

Because of all of the above reasons, we feel that Blockin is a great choice for implementing Sign-In with Ethereum on Scaffold.

### **UI vs Modal**
This pull requests showcases Blockin's all-in-one UI display for a) selecting a chain, b) connecting your wallet, and c) signing in. The display does, in our opinion, clean up some of the code from the top right and display it in a neater, easier to use fashion. However, it does limit a lot of the customization opportunities that the Scaffold components offer. If you want to change how something looks or add some new functionality, you would have to get it approved and changed in the Blockin library instead of just updating the file yourself. 

There are a couple options that we would like to propose. We do not mind which one is picked.
- Current : This is the one implemented in the pull request currently. We, by default, show the Blockin all-in-one UI display. The old display is included in Account.jsx but commented out. If users would like to switch to the old, more customizable components, all they have to do is comment out the Blockin one and uncomment the old one.
- Option 2 : This can also be switched around. The existing UI will still be displayed by default, but we will provide the Blockin UI display commented out. Users can switch between the two.
- Option 3 : The Blockin UI display could be scrapped altogether. The Sign In modal and only the modal can also be exported from Blockin, so we could just add a button right next to the connect / disconnect button, and upon click, the modal will open up. This will be almost identical to how the Web3Modal looks and works.

**### Implementation Details**
Details for how to setup and run the updated Sign-In with Ethereum functionality can be found in views/SignInWithEthereum.jsx or the Sign-In with Ethereum tab. We propose that by default, all sign-in functionality is disabled (which means no functionality changes), but this Sign-In with Ethereum tab will be added to the main tabs and show how to enable it.

Backend - We introduce a new folder called node-backend in the packages folder. This is a backend API template using Express.js and Blockin. It can be run by calling yarn run-node-backend from the root scaffold directory. The template code already implements what is needed for it to support Sign-In with Ethereum.

Frontend - Similar to the backend, the template code already implements a working version of Sign-In with Ethereum.

Further customization and configuration can be added to both the frontend and backend to support an application's needs. 

### **Conclusion**
I would love to get SIWE and Blockin integrated into ScaffoldETH as I think this could be useful to many, many developers out there. I know there will definitely be suggestions, questions, concerns, everything :). I will try and respond to this thread as quickly as I can. If there are new updates needed for the pull request, I also will try my best to do so in a timely manner.

### CODE REVIEW

**Comment by codenamejason** [comment]
@trevormil sorry for delay on this. I am going to create a branch called eth-sign-in in the examples repo for you to PR to.

**Comment by trevormil** [comment]
> @trevormil sorry for delay on this. I am going to create a branch called eth-sign-in in the examples repo for you to PR to. https://github.com/scaffold-eth/scaffold-eth-examples/tree/eth-sign-in

Ok thanks @codenamejason. I will push to this branch.

As mentioned though in the initial post for this thread, I did consider the tradeoff between introducing this as a new flavor / example vs in the main repository itself. And, I do believe that it adds a lot of value to the main repository. Sign-In with Ethereum is a large and growing part of Ethereum development, and Scaffold doesn't currently support this. 

If this is something of interest, I would love to continue to work on this branch with the goal of eventually getting it added to the main repo. If this is the case, I would appreciate to hear some feedback or next steps to proceed. If not, that is totally okay too.

**Comment by codenamejason** [comment]
@austintgriffith what do you think of the above comment?

**Comment by trevormil** [comment]
Do you think I could get some closure on this? Totally fine either way: if you do or do not want to pursue getting it added to the main branch. Would just like an update. Thanks

It is currently added into the examples repo in the eth-sign-in repo.

**Pull request closed without merging**
