### PR TITLE
Added celo blockchain networks to scaffold eth

### PR DESCRIPTION
**Pull request by eliashezron**
I added celo blockchain networks to hardhat config file and react constants file to allow celo blockchain developers easily get started with scaffold-eth.

### CODE REVIEW

**Review by codenamejason — COMMENTED** [review]
why all the changes to `YourContract.sol` this PR is more than just adding a network.

**Comment by eliashezron** [comment]
It's because of prettier that just included double quotes to the contract.sol file when I saved it.

Check out the changes and you'll see that nothing was added to those files.

**Comment by codenamejason** [comment]
@eliashezron `YourContract.sol` has a bunch of stuff added 🤔

**Comment by eliashezron** [comment]
Let me do another PR

**Pull request closed without merging**
