### PR TITLE
Added comments regarding deprecated networks.

### PR DESCRIPTION
**Pull request by EngrGord**
This pull request is due to the deprecation of Kovan, Ropsten, Rinkeby testnets which is going to be discontinued by Infura and Alchemy by October 5.
This PR also moves these networks down the list of networks. 
Also added goerli Arbitrum and goerli Optimism in the network list.

### CODE REVIEW

**Comment by carletex** [comment]
@codenamejason Yeah, I think we should removed them completely.

Even if some of them are still up, alchemy/infura/etherscan/etc just deprecated them.

@EngrGord Could you update? Thanks! :)

**Comment by EngrGord** [comment]
Sure!

**Comment by EngrGord** [comment]
@codenamejason @carletex The deprecated networks has been removed from this PR. Thanks

**Review by codenamejason — APPROVED** [review]
LGTM!

**Pull request merged**
