### PR TITLE
Issue 644 – Add support for displaying Balance in USD or ETH

### PR DESCRIPTION
**Pull request by NeoDaoist**
https://github.com/scaffold-eth/scaffold-eth/issues/644

### CODE REVIEW

**Comment by NeoDaoist** [comment]
Feel free to reject this PR. I see how my previous unrelated commits are mixed in, even tho the diff itself is fine. Whoops

**Comment by codenamejason** [comment]
Oh, we gonna merge it ser 😆 Thanks for the Pr, much appreciated. Have you joined speedrunethereum.com yet as a buidler? @NeoDaoist

**Review by codenamejason — APPROVED** [review]
🔥🔥🔥

**Comment by NeoDaoist** [comment]
> Oh, we gonna merge it ser 😆 Thanks for the Pr, much appreciated. Have you joined speedrunethereum.com yet as a buidler? @NeoDaoist

OK sweet! Yes I have 😎  https://speedrunethereum.com/builders/0x4BBa239C9cC83619228457502227D801e4738bA0

**Pull request merged**
